### ISSUE TITLE
  Expo.Audio.setIsEnabled(true);

### ISSUE THREAD

**Issue by S1ROZHA** [clearfunction/cf-soundboard#3]
Try buid on expo 
Expo.Audio.setIsEnabled(true);
is undefinied function

**Comment by S1ROZHA** [comment]
fix this new api Expo.Audio.setIsEnabledAsync(value)

**Comment by drmohundro** [comment]
Resolved in 3ef5c66e4b8416e174f09c0a0f100f5ad4fc9b04.
